services:
  mongodb:
    image: mongo:${MONGODB_VER:-7.0.14}
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    expose:
      - $MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build:
      context: app
      dockerfile: ./Dockerfile
    command: /usr/src/app/docker.app.js
    restart: unless-stopped
    env_file: ./.env
    volumes:
        - ./app:/usr/src/app
        - .env:/app/.env:ro
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - WEB_PORT=$NODE_DOCKER_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
  miner:
    depends_on:
      - mongodb
    build:
      context: app
      dockerfile: ./Dockerfile
    command: /usr/src/app/docker.miner.js
    restart: unless-stopped
    env_file: ./.env
    volumes:
        - ./app:/usr/src/app
        - .env:/app/.env:ro
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

volumes:
  db:
